/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter:3.0.3")
    api("org.springframework.boot:spring-boot-starter-web:3.0.3")
    api("ai.razzle:java-sdk:0.3.0-56-SNAPSHOT")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:3.0.3")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.3")
}

group = "ai.razzle"
version = "0.0.1-SNAPSHOT"
description = "razzle-java-apps"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
